## Load packages

In [7]:
pip install lxml

Requirement already satisfied: lxml in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (4.9.3)
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install missingno

Collecting missingno
  Using cached missingno-0.5.2-py3-none-any.whl (8.7 kB)
Requirement already satisfied: numpy in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from missingno) (1.24.3)
Requirement already satisfied: matplotlib in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from missingno) (3.7.2)
Requirement already satisfied: scipy in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from missingno) (1.11.1)
Collecting seaborn (from missingno)
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Requirement already satisfied: contourpy>=1.0.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (4.41.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib->missingno) (2.8.2)
Collecting pandas>=0.25 (from seaborn->missingno)
  Obtaining dependency information for pandas>=0.25 from https://files.pythonhosted.org/packages/8f/bb/aea1fbeed5b474cb8634364718abe9030d7cc7a30bf51f40bd494bbc89a2/pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting pytz>=2020.1 (from pandas>=0.25->seaborn->missingno)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas>=0.25->seaborn->missingno)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: six>=1.5 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.16.0)
Downloading pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 8.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: pytz, tzdata, pandas, seaborn, missingno
Successfully installed missingno-0.5.2 pandas-2.0.3 pytz-2023.3 seaborn-0.12.2 tzdata-2023.3
Note: you may need to restart the kernel to use updated packages.

In [9]:
%pip install ydata_profiling

Collecting ydata_profiling
  Obtaining dependency information for ydata_profiling from https://files.pythonhosted.org/packages/07/ba/f229e94517d033b427b3e856e1429872ce8368601ef534cad3c14a40f99e/ydata_profiling-4.3.1-py2.py3-none-any.whl.metadata
  Downloading ydata_profiling-4.3.1-py2.py3-none-any.whl.metadata (19 kB)
Collecting scipy<1.11,>=1.4.1 (from ydata_profiling)
  Using cached scipy-1.10.1-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Requirement already satisfied: pandas!=1.4.0,<2.1,>1.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from ydata_profiling) (2.0.3)
Requirement already satisfied: matplotlib<4,>=3.2 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from ydata_profiling) (3.7.2)
Collecting pydantic<2,>=1.8.1 (from ydata_profiling)
  Obtaining dependency information for pydantic<2,>=1.8.1 from https://files.pythonhosted.org/packages/93/63/c2b91f7482bf8e5b7166dba6558287d906587f269158b8fad1146031fdc3/pydantic-1.10.11-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading pydantic-1.10.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 3.2 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from ydata_profiling) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from ydata_profiling) (3.1.2)
Collecting visions[type_image_path]==0.7.5 (from ydata_profiling)
  Using cached visions-0.7.5-py3-none-any.whl (102 kB)
Collecting numpy<1.24,>=1.16.0 (from ydata_profiling)
  Using cached numpy-1.23.5-cp311-cp311-macosx_11_0_arm64.whl (13.3 MB)
Collecting htmlmin==0.1.12 (from ydata_profiling)
  Using cached htmlmin-0.1.12-py3-none-any.whl
Collecting phik<0.13,>=0.11.1 (from ydata_profiling)
  Using cached phik-0.12.3-cp311-cp311-macosx_11_0_arm64.whl (649 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from ydata_profiling) (2.31.0)
Collecting tqdm<5,>=4.48.2 (from ydata_profiling)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from ydata_profiling) (0.12.2)
Collecting multimethod<2,>=1.4 (from ydata_profiling)
  Using cached multimethod-1.9.1-py3-none-any.whl (10 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata_profiling)
  Using cached statsmodels-0.14.0-cp311-cp311-macosx_11_0_arm64.whl (9.4 MB)
Collecting typeguard<3,>=2.13.2 (from ydata_profiling)
  Using cached typeguard-2.13.3-py3-none-any.whl (17 kB)
Collecting imagehash==4.3.1 (from ydata_profiling)
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Collecting wordcloud>=1.9.1 (from ydata_profiling)
  Using cached wordcloud-1.9.2-cp311-cp311-macosx_12_0_arm64.whl
Collecting dacite>=1.8 (from ydata_profiling)
  Obtaining dependency information for dacite>=1.8 from https://files.pythonhosted.org/packages/21/0f/cf0943f4f55f0fbc7c6bd60caf1343061dff818b02af5a0d444e473bb78d/dacite-1.8.1-py3-none-any.whl.metadata
  Downloading dacite-1.8.1-py3-none-any.whl.metadata (15 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata_profiling)
  Using cached PyWavelets-1.4.1-cp311-cp311-macosx_11_0_arm64.whl (4.3 MB)
Requirement already satisfied: pillow in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from imagehash==4.3.1->ydata_profiling) (10.0.0)
Requirement already satisfied: attrs>=19.3.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from visions[type_image_path]==0.7.5->ydata_profiling) (23.1.0)
Collecting networkx>=2.4 (from visions[type_image_path]==0.7.5->ydata_profiling)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting tangled-up-in-unicode>=0.0.4 (from visions[type_image_path]==0.7.5->ydata_profiling)
  Using cached tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata_profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (4.41.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (23.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from matplotlib<4,>=3.2->ydata_profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from pandas!=1.4.0,<2.1,>1.1->ydata_profiling) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from pandas!=1.4.0,<2.1,>1.1->ydata_profiling) (2023.3)
Collecting joblib>=0.14.1 (from phik<0.13,>=0.11.1->ydata_profiling)
  Obtaining dependency information for joblib>=0.14.1 from https://files.pythonhosted.org/packages/28/08/9dcdaa5aac4634e4c23af26d92121f7ce445c630efa0d3037881ae2407fb/joblib-1.3.1-py3-none-any.whl.metadata
  Using cached joblib-1.3.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from pydantic<2,>=1.8.1->ydata_profiling) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata_profiling) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata_profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata_profiling) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata_profiling) (2023.5.7)
Collecting patsy>=0.5.2 (from statsmodels<1,>=0.13.2->ydata_profiling)
  Using cached patsy-0.5.3-py2.py3-none-any.whl (233 kB)
Requirement already satisfied: six in /Users/bimladanu/Documents/Github/Neufische_Bootcamp/06July_Image_Modeling/ds-image-modeling/.venv/lib/python3.11/site-packages (from patsy>=0.5.2->statsmodels<1,>=0.13.2->ydata_profiling) (1.16.0)
Using cached ydata_profiling-4.3.1-py2.py3-none-any.whl (352 kB)
Using cached dacite-1.8.1-py3-none-any.whl (14 kB)
Downloading pydantic-1.10.11-cp311-cp311-macosx_11_0_arm64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 9.4 MB/s eta 0:00:00:00:0100:01
Using cached joblib-1.3.1-py3-none-any.whl (301 kB)
Installing collected packages: htmlmin, typeguard, tqdm, tangled-up-in-unicode, pydantic, numpy, networkx, multimethod, joblib, dacite, scipy, PyWavelets, patsy, visions, statsmodels, imagehash, wordcloud, phik, ydata_profiling
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.3
    Uninstalling numpy-1.24.3:
      Successfully uninstalled numpy-1.24.3
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.1
    Uninstalling scipy-1.11.1:
      Successfully uninstalled scipy-1.11.1
Successfully installed PyWavelets-1.4.1 dacite-1.8.1 htmlmin-0.1.12 imagehash-4.3.1 joblib-1.3.1 multimethod-1.9.1 networkx-3.1 numpy-1.23.5 patsy-0.5.3 phik-0.12.3 pydantic-1.10.11 scipy-1.10.1 statsmodels-0.14.0 tangled-up-in-unicode-0.2.0 tqdm-4.65.0 typeguard-2.13.3 visions-0.7.5 wordcloud-1.9.2 ydata_profiling-4.3.1
Note: you may need to restart the kernel to use updated packages.

In [11]:
pip install chardet

Collecting chardet
  Downloading chardet-5.1.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 2.8 MB/s eta 0:00:00a 0:00:01
Installing collected packages: chardet
Successfully installed chardet-5.1.0
Note: you may need to restart the kernel to use updated packages.

SyntaxError: invalid syntax (2365568199.py, line 1)

In [13]:
from lxml import objectify # pip install lxml
import chardet
import pandas as pd
import missingno as msno # run first '%pip install missingno'
from ydata_profiling import ProfileReport # run first '%pip install ydata_profiling'

from models.tools import show_info, get_alerts, dump_missing

ModuleNotFoundError: No module named 'models.tools'

## OPSD

> https://open-power-system-data.org/

In [2]:
input_file = "/Users/jshen/Library/CloudStorage/Dropbox/_share/capstone/OPSD/renewable_power_plants_DE.csv"

df = pd.read_csv(input_file, delimiter=',', encoding="utf-8", parse_dates=["commissioning_date"])

df.head()

/var/folders/jv/dryp57w96c1bw9d181ktn53c0000gn/T/ipykernel_2086/1586768897.py:3: DtypeWarning: Columns (14,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file, delimiter=',', encoding="utf-8", parse_dates=["commissioning_date"])

,electrical_capacity,energy_source_level_1,energy_source_level_2,energy_source_level_3,technology,data_source,nuts_1_region,nuts_2_region,nuts_3_region,lon,...,postcode,address,federal_state,commissioning_date,decommissioning_date,voltage_level,eeg_id,dso,dso_id,tso
0,0.080,Renewable energy,Bioenergy,Sewage and landfill gas,Sewage and landfill gas,TransnetBW,DE1,DE13,DE135,8.578018,...,78727.0,NaN,Baden-Württemberg,1900-01-02,NaN,medium voltage,NaN,Netze BW GmbH,10000843.0,TransnetBW
1,0.015,Renewable energy,Hydro,NaN,Run-of-river,TenneT,DE2,DE25,DE25C,10.881562,...,91757.0,NaN,Brandenburg,1901-01-01,NaN,low voltage,NaN,Stadtwerke Treuchtlingen,10001282.0,TenneT
2,0.055,Renewable energy,Hydro,NaN,Run-of-river,TransnetBW,DE1,DE14,DE148,9.664273,...,88255.0,NaN,Baden-Württemberg,1901-01-01,NaN,low voltage / medium voltage,NaN,Netze BW GmbH,10000843.0,TransnetBW
3,0.120,Renewable energy,Hydro,NaN,Run-of-river,TransnetBW,DE1,DE14,DE148,9.664273,...,88255.0,NaN,Baden-Württemberg,1901-01-01,NaN,low voltage,NaN,Netze BW GmbH,10000843.0,TransnetBW
4,0.044,Renewable energy,Hydro,NaN,Run-of-river,TransnetBW,DE1,DE12,DE128,8.775571,...,69245.0,NaN,Baden-Württemberg,1901-07-01,NaN,low voltage,NaN,Syna GmbH,10001495.0,TransnetBW

### Columns
| Name                | Description                                                                   | Type     |
|---------------------|-------------------------------------------------------------------------------|----------|
| electrical_capacity | Installed electrical capacity in MW                                           | number   |
| energy_source_level_1 | Type of energy source (e.g. Renewable energy)                               | string   |
| energy_source_level_2 | Type of energy source (e.g. Wind, Solar)                                   | string   |
| energy_source_level_3 | Subtype of energy source (e.g. Biomass and biogas)                         | string   |
| technology          | Technology to harvest energy source (e.g. Onshore, Photovoltaics)             | string   |
| data_source         | Source of database entry                                                      | string   |
| nuts_1_region       | The code of the NUTS 1 region the facility is in (e.g. DE1)                   | string   |
| nuts_2_region       | The code of the NUTS 2 region the facility is in (e.g. DE11)                  | string   |
| nuts_3_region       | The code of the NUTS 3 region the facility is in (e.g. DE111)                 | string   |
| lon                 | Longitude coordinates                                                          | number   |
| lat                 | Latitude coordinates                                                           | number   |
| municipality        | Name of German Gemeinde (municipality)                                        | string   |
| municipality_code   | German Gemeindenummer (municipalitiy number)                                  | string   |
| postcode            | German zip-code                                                               | string   |
| address             | Street name or name of land parcel                                            | string   |
| federal_state       | Name of German administrative level 'Bundesland'                              | string   |
| commissioning_date  | Date of commissioning of specific unit                                        | date     |
| decommissioning_date| Date of decommissioning of specific unit                                      | date     |
| voltage_level       | Voltage level of grid connection                                              | string   |
| eeg_id              | Power plant EEG (German feed-in tariff law) remuneration number               | string   |
| dso                 | Name of distribution system operator of the region the plant is located in    | string   |
| dso_id              | Company number of German distribution grid operator                           | string   |
| tso                 | Name of transmission system operator of the area the plant is located         | string   |

Refer to:
> https://data.open-power-system-data.org/renewable_power_plants/2020-08-25/datapackage.json

In [3]:
df.iloc[:, [14, 19]].columns

Index(['address', 'eeg_id'], dtype='object')

In [4]:
# Detect encoding of the XML file
# with open(input_file, 'rb') as f:
#     result = chardet.detect(f.read())
# encoding = result['encoding']

# print(encoding)

In [5]:
# Columns can be dropped right away
# "energy_source_level_1" - single value
# "decommissioning_date" - all null

"""
"energy_source_level_3" has 1754346 (99.2%) missing values
"municipality" has 1073178 (60.7%) missing values
"address" has 1764642 (99.8%) missing values
"decommissioning_date" has 1768745 (100.0%) missing values
"eeg_id" has 1768227 (> 99.9%) missing values
"""

show_info(df)

,Column,Dtype,Non-Null Count,Unique Count,Unique Values
0,electrical_capacity,float64,1768745,41321,
1,energy_source_level_1,object,1768745,1,{'Renewable energy': 1768745}
2,energy_source_level_2,object,1768745,5,"{'Solar': 1725093, 'Wind': 22281, 'Bioenergy':..."
3,energy_source_level_3,object,14399,2,"{'Biomass and biogas': 13923, 'Sewage and land..."
4,technology,object,1768745,8,"{'Photovoltaics': 1724918, 'Onshore': 21547, '..."
5,data_source,object,1768745,6,"{'TenneT': 736559, 'Amprion': 508673, 'Transne..."
6,nuts_1_region,object,1768070,16,
7,nuts_2_region,object,1768070,38,
8,nuts_3_region,object,1768070,401,
9,lon,float64,1767459,8171,
10,lat,float64,1767459,8171,
11,municipality,object,695567,16008,
12,municipality_code,float64,1734885,10824,
13,postcode,float64,1768729,8304,
14,address,object,4103,3954,
15,federal_state,object,1768739,20,
16,commissioning_date,datetime64[ns],1768744,10157,
17,decommissioning_date,float64,0,0,{}
18,voltage_level,object,1735603,7,"{'low voltage': 1639745, 'medium voltage': 607..."
19,eeg_id,object,518,518,
20,dso,object,1735604,898,
21,dso_id,float64,1734845,854,
22,tso,object,1734858,4,"{'TenneT': 736559, 'Amprion': 508673, 'Transne..."

In [6]:
# Get the latest date in the OPSD dataset
df["commissioning_date"].unique().max() # Timestamp('2018-06-22 00:00:00')

Timestamp('2018-06-22 00:00:00')

In [7]:
df_profile = ProfileReport(df, title="Profiling Report")
# Export the profile report
output_report = "output/df_profile.html"
df_profile.to_file(output_report)

# Open the report in the default browser
# !open {output_report}

# Get the alters from the profiling report
get_alerts(output_report)

Summarize dataset: 100%|██████████| 69/69 [01:14<00:00,  1.08s/it, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.93s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 146.41it/s]

Constant: energy_source_level_1 has constant value ""
High correlation: lon is highly overall correlated with municipality_code and 2 other fields
High correlation: lat is highly overall correlated with postcode and 3 other fields
High correlation: municipality_code is highly overall correlated with lon and 5 other fields
High correlation: postcode is highly overall correlated with lat and 5 other fields
High correlation: energy_source_level_2 is highly overall correlated with energy_source_level_3 and 1 other fields
High correlation: energy_source_level_3 is highly overall correlated with energy_source_level_2 and 1 other fields
High correlation: technology is highly overall correlated with energy_source_level_2 and 1 other fields
High correlation: data_source is highly overall correlated with municipality_code and 5 other fields
High correlation: nuts_1_region is highly overall correlated with lat and 6 other fields
High correlation: nuts_2_region is highly overall correlated with lon and 7 other fields
High correlation: federal_state is highly overall correlated with lat and 6 other fields
High correlation: tso is highly overall correlated with lon and 6 other fields
Imbalance: energy_source_level_2 is highly imbalanced (91.3%)
Imbalance: energy_source_level_3 is highly imbalanced (79.0%)
Imbalance: technology is highly imbalanced (93.0%)
Imbalance: voltage_level is highly imbalanced (86.1%)
Missing: energy_source_level_3 has 1754346 (99.2%) missing values
Missing: municipality has 1073178 (60.7%) missing values
Missing: municipality_code has 33860 (1.9%) missing values
Missing: address has 1764642 (99.8%) missing values
Missing: decommissioning_date has 1768745 (100.0%) missing values
Missing: voltage_level has 33142 (1.9%) missing values
Missing: eeg_id has 1768227 (> 99.9%) missing values
Missing: dso has 33141 (1.9%) missing values
Missing: dso_id has 33900 (1.9%) missing values
Missing: tso has 33887 (1.9%) missing values
Skewed: electrical_capacity is highly skewed (γ1 = 61.20464339)
Unsupported: decommissioning_date is an unsupported type, check if it needs cleaning or further analysis

## MaStR

- Since August 2014 the BNetzA is responsible to publish the renewable power plants register. The legal framework for the register is specified in the EEG 2014 (German) (English). All power plants are listed in a new format: two separate MS-Excel and CSV files for roof-mounted PV power plants 'PV-Datenmeldungen' and all other renewable power plants ' Anlagenregister'.
- From the beginning of 2019, BNetzA has switched to the Marktstammdatenregister (**MaStR**, central register for installation data). This is, however, not used yet for OPSD data. We will change to using the MaStR most likely for the 2020 version of the OPSD data package.
- **MaStR** https://www.marktstammdatenregister.de/MaStR

In [8]:

# Downloaded from
# https://www.marktstammdatenregister.de/MaStR/Datendownload
input_file = "/Users/jshen/Library/CloudStorage/Dropbox/_share/capstone/MaStR/Gesamtdatenexport_20230401_22.2/AnlagenEegSolar_2.xml" # 


# Detect encoding of the XML file
# with open(input_file, 'rb') as f:
#     result = chardet.detect(f.read())
# encoding = result['encoding']

# print(encoding) # UTF-16

encoding = "UTF-16"
# Use detected encoding to read the file
parsed = objectify.parse(open(input_file, 'r', encoding=encoding))
root = parsed.getroot()

In [9]:
print(root.tag)
# for child in root.getchildren():
#     print(child.tag) # EinheitSolar

AnlagenEegSolar

In [10]:
data = []

for AnlageEegSolar in root.AnlageEegSolar:
    el_data = {}
    for child in AnlageEegSolar.getchildren():
        el_data[child.tag] = child.text
    data.append(el_data)


df = pd.DataFrame(data)

# TO-DO:
# df.rename(columns={
#     "Registrierungsdatum": "RegistrationDate",
#     "DatumLetzteAktualisierung": "LastUpdatedDate",
#     "EegInbetriebnahmedatum": "EegCommissioningDate",
#     "EegMaStRNummer": "EegMaStRNumber",
#     "InanspruchnahmeZahlungNachEeg": "ClaimPaymentAfterEeg",
#     "AnlagenschluesselEeg": "PlantKeyEeg",
#     "AnlagenkennzifferAnlagenregister_nv": "PlantIdentificationNumberPlantRegister_nv",
#     "InstallierteLeistung": "InstalledCapacity",
#     "RegistrierungsnummerPvMeldeportal_nv": "RegistrationNumberPvReportingPortal_nv",
#     "AusschreibungZuschlag": "TenderAward",
#     "AnlageBetriebsstatus": "PlantOperatingStatus",
#     "VerknuepfteEinheitenMaStRNummern": "LinkedUnitsMaStRNumbers"
# }, 
# inplace=True,
# )


df.head()

,Registrierungsdatum,DatumLetzteAktualisierung,EegInbetriebnahmedatum,EegMaStRNummer,InanspruchnahmeZahlungNachEeg,AnlagenkennzifferAnlagenregister_nv,InstallierteLeistung,RegistrierungsnummerPvMeldeportal_nv,AusschreibungZuschlag,AnlageBetriebsstatus,VerknuepfteEinheitenMaStRNummern,AnlagenschluesselEeg,RegistrierungsnummerPvMeldeportal,MieterstromZugeordnet,AnlagenkennzifferAnlagenregister,MieterstromMeldedatum,MieterstromErsteZuordnungZuschlag,ZugeordneteGebotsmenge,Zuschlagsnummer
0,2019-03-16,2019-03-16T09:31:43.4713222,2010-06-30,EEG990585199131,1,0,18.540,0,0,35,SEE975559329271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-03-19,2020-08-22T11:37:06.9681055,2001-08-14,EEG922874197672,1,0,9.000,0,0,35,SEE927346874891,E11297010000000000000000046200001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-03-16,2019-05-29T18:09:40.9440174,2011-12-08,EEG900470039305,1,0,7.150,1,0,35,SEE950213485692,E30710010050401004029000S00300887,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-03-16,2019-03-16T09:29:09.8433914,2011-05-27,EEG946109380318,1,0,5.760,0,0,35,SEE968861602651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-03-16,2019-11-11T15:54:21.1402894,2008-07-07,EEG987970624767,1,0,15.600,0,0,35,SEE913120476566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
show_info(df)

,Column,Dtype,Non-Null Count,Unique Count,Unique Values
0,Registrierungsdatum,object,100000,772,
1,DatumLetzteAktualisierung,object,100000,99428,
2,EegInbetriebnahmedatum,object,100000,6186,
3,EegMaStRNummer,object,100000,100000,
4,InanspruchnahmeZahlungNachEeg,object,98547,2,"{'1': 97671, '0': 876}"
5,AnlagenkennzifferAnlagenregister_nv,object,100000,2,"{'0': 69769, '1': 30231}"
6,InstallierteLeistung,object,100000,10057,
7,RegistrierungsnummerPvMeldeportal_nv,object,100000,2,"{'0': 82489, '1': 17511}"
8,AusschreibungZuschlag,object,98048,2,"{'0': 97898, '1': 150}"
9,AnlageBetriebsstatus,object,100000,4,"{'35': 99628, '38': 344, '37': 27, '31': 1}"
10,VerknuepfteEinheitenMaStRNummern,object,100000,100000,
11,AnlagenschluesselEeg,object,74867,74536,
12,RegistrierungsnummerPvMeldeportal,object,37245,36243,
13,MieterstromZugeordnet,object,25077,2,"{'0': 24784, '1': 293}"
14,AnlagenkennzifferAnlagenregister,object,141,140,
15,MieterstromMeldedatum,object,234,82,
16,MieterstromErsteZuordnungZuschlag,object,234,132,
17,ZugeordneteGebotsmenge,object,77,69,
18,Zuschlagsnummer,object,69,61,

In [12]:
dump_missing(df)

Out of 100000 entries:

                                   Amount  Percentage
InanspruchnahmeZahlungNachEeg        1453        1.45
AusschreibungZuschlag                1952        1.95
AnlagenschluesselEeg                25133       25.13
RegistrierungsnummerPvMeldeportal   62755       62.76
MieterstromZugeordnet               74923       74.92
AnlagenkennzifferAnlagenregister    99859       99.86
MieterstromMeldedatum               99766       99.77
MieterstromErsteZuordnungZuschlag   99766       99.77
ZugeordneteGebotsmenge              99923       99.92
Zuschlagsnummer                     99931       99.93

In [13]:
import xml.etree.ElementTree as ET

# Parse XML file
input_file = "/Users/jshen/Library/CloudStorage/Dropbox/_share/capstone/MaStR/Gesamtdatenexport_20230401_22.2/EinheitenSolar_1.xml"

tree = ET.parse(input_file)
root = tree.getroot()

# Define a list of dictionaries to hold the data
data = []

# Iterate over all 'EinheitSolar' elements in the file
for einheit in root.findall('EinheitSolar'):
    # Each 'einheit' is a dictionary
    einheit_data = {}
    
    # Iterate over all children elements of 'einheit'
    for child in einheit:
        # Use the tag name as a dictionary key and the text as the value
        einheit_data[child.tag] = child.text
    
    # Append this 'einheit' to the list
    data.append(einheit_data)

# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(data)

pd.set_option('display.max_columns', 100)

# Now 'df' is a pandas DataFrame that contains all information in the XML
df.head()

,EinheitMastrNummer,DatumLetzteAktualisierung,LokationMaStRNummer,NetzbetreiberpruefungStatus,NetzbetreiberpruefungDatum,AnlagenbetreiberMastrNummer,Land,Bundesland,Landkreis,Gemeinde,Gemeindeschluessel,Postleitzahl,Ort,Registrierungsdatum,Inbetriebnahmedatum,EinheitSystemstatus,EinheitBetriebsstatus,NichtVorhandenInMigriertenEinheiten,NameStromerzeugungseinheit,Weic_nv,Kraftwerksnummer_nv,Energietraeger,Bruttoleistung,Nettonennleistung,FernsteuerbarkeitNb,Einspeisungsart,ZugeordneteWirkleistungWechselrichter,GemeinsamerWechselrichterMitSpeicher,AnzahlModule,Lage,Leistungsbegrenzung,EinheitlicheAusrichtungUndNeigungswinkel,Hauptausrichtung,HauptausrichtungNeigungswinkel,Nutzungsbereich,EegMaStRNummer,Nebenausrichtung,NebenausrichtungNeigungswinkel,Strasse,StrasseNichtGefunden,Hausnummer_nv,HausnummerNichtGefunden,Laengengrad,Breitengrad,FernsteuerbarkeitDr,Hausnummer,Adresszusatz,FernsteuerbarkeitDv,Gemarkung,FlurFlurstuecknummern,AnschlussAnHoechstOderHochSpannung,InAnspruchGenommeneFlaeche,ArtDerFlaecheIds,DatumDesBetreiberwechsels,DatumRegistrierungDesBetreiberwechsels,DatumEndgueltigeStilllegung,InAnspruchGenommeneAckerflaeche,GeplantesInbetriebnahmedatum,GenMastrNummer,Einsatzverantwortlicher,WeicDisplayName,DatumBeginnVoruebergehendeStilllegung,DatumWiederaufnahmeBetrieb,Buergerenergie,Kraftwerksnummer
0,SEE984033548619,2020-02-20T16:28:35.2508122,SEL948991715391,1,2020-02-25,ABR949444220202,84,1409,Münster,Münster,05515000,48147,Münster,2019-02-01,2007-07-20,472,35,0,Photovoltaikanlage ERWin4,0,0,2495,3.960,3.960,0,688,4.000,1450,22,853,802,1,699,809,713,EEG920083771065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SEE901901460125,2021-07-15T07:54:37.8637095,SEL982068309366,1,2019-01-31,ABR930055871044,84,1402,Ostalbkreis,Schwäbisch Gmünd,08136065,73529,Schwäbisch Gmünd,2019-01-31,2013-01-31,472,35,0,man-power,0,0,2495,7.410,7.410,0,689,8.300,1450,38,853,803,1,699,809,713,EEG943811805092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SEE983679054270,2019-05-28T08:26:38.0316692,SEL906699064968,1,2019-07-22,ABR983885950021,84,1400,Havelland,Nauen,12063208,14641,Nauen,2019-01-31,2016-02-19,472,35,0,eigene PVA,0,0,2495,5.040,5.000,0,689,5.000,1449,16,853,803,1,699,809,713,EEG963355832040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SEE978732598938,2020-12-07T08:19:07.9860793,SEL996128012264,1,2020-12-16,ABR980052996196,84,1403,Regensburg,Pentling,09375180,93080,Pentling,2019-01-31,2016-12-16,472,35,0,Photovoltaik EFH Löbert - Mattinger Weg 6,0,0,2495,6.360,6.000,0,689,6.000,1448,24,853,1535,1,700,809,713,EEG957216544098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SEE970592691989,2021-01-25T11:18:30.0433603,SEL975715515692,1,2021-10-22,ABR970373690446,84,1412,Saarlouis,Saarlouis,10044115,66740,Saarlouis,2019-01-31,2011-12-08,472,35,0,"PV-Anlage 7,2 (Voll)",0,0,2495,7.200,7.200,0,689,7.600,1450,30,853,802,0,701,809,713,EEG932405876693,697,809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
pd.set_option('display.max_rows', 100)
show_info(df)
#pd.set_option('display.max_rows', None)

,Column,Dtype,Non-Null Count,Unique Count,Unique Values
0,EinheitMastrNummer,object,100000,100000,
1,DatumLetzteAktualisierung,object,100000,56705,
2,LokationMaStRNummer,object,99662,95327,
3,NetzbetreiberpruefungStatus,object,100000,2,"{'1': 86406, '0': 13594}"
4,NetzbetreiberpruefungDatum,object,99925,1473,
5,AnlagenbetreiberMastrNummer,object,99737,77832,
6,Land,object,100000,1,{'84': 100000}
7,Bundesland,object,99999,16,
8,Landkreis,object,99999,380,
9,Gemeinde,object,99999,8266,
10,Gemeindeschluessel,object,99999,8596,
11,Postleitzahl,object,99999,7562,
12,Ort,object,99999,8307,
13,Registrierungsdatum,object,100000,849,
14,Inbetriebnahmedatum,object,99925,6252,
15,EinheitSystemstatus,object,100000,1,{'472': 100000}
16,EinheitBetriebsstatus,object,100000,4,"{'35': 99545, '38': 343, '31': 75, '37': 37}"
17,NichtVorhandenInMigriertenEinheiten,object,100000,1,{'0': 100000}
18,NameStromerzeugungseinheit,object,100000,55114,
19,Weic_nv,object,100000,2,"{'0': 94773, '1': 5227}"
20,Kraftwerksnummer_nv,object,100000,2,"{'0': 99992, '1': 8}"
21,Energietraeger,object,100000,1,{'2495': 100000}
22,Bruttoleistung,object,100000,10617,
23,Nettonennleistung,object,100000,7101,
24,FernsteuerbarkeitNb,object,98571,2,"{'0': 77007, '1': 21564}"
25,Einspeisungsart,object,99301,2,"{'689': 50709, '688': 48592}"
26,ZugeordneteWirkleistungWechselrichter,object,99989,5680,
27,GemeinsamerWechselrichterMitSpeicher,object,99104,3,"{'1450': 83348, '1448': 9775, '1449': 5981}"
28,AnzahlModule,object,98464,2346,
29,Lage,object,99995,4,"{'853': 97262, '2484': 1847, '852': 881, '2961..."
30,Leistungsbegrenzung,object,98303,5,"{'802': 67221, '803': 26626, '1535': 2894, '80..."
31,EinheitlicheAusrichtungUndNeigungswinkel,object,98762,2,"{'1': 79732, '0': 19030}"
32,Hauptausrichtung,object,99147,10,
33,HauptausrichtungNeigungswinkel,object,98568,6,"{'809': 55860, '808': 23102, '810': 18074, '80..."
34,Nutzungsbereich,object,92385,6,"{'713': 62828, '716': 14622, '714': 7809, '718..."
35,EegMaStRNummer,object,99925,99925,
36,Nebenausrichtung,object,18374,10,
37,NebenausrichtungNeigungswinkel,object,18036,6,"{'809': 8898, '810': 5659, '808': 3176, '806':..."
38,Strasse,object,10667,6864,
39,StrasseNichtGefunden,object,11741,2,"{'0': 10844, '1': 897}"
40,Hausnummer_nv,object,11741,2,"{'0': 11207, '1': 534}"
41,HausnummerNichtGefunden,object,11741,2,"{'0': 10408, '1': 1333}"
42,Laengengrad,object,11741,9755,
43,Breitengrad,object,11741,9580,
44,FernsteuerbarkeitDr,object,5831,2,"{'0': 5371, '1': 460}"
45,Hausnummer,object,10150,793,
46,Adresszusatz,object,835,716,
47,FernsteuerbarkeitDv,object,5813,2,"{'0': 3336, '1': 2477}"
48,Gemarkung,object,2299,1691,
49,FlurFlurstuecknummern,object,2299,1983,
50,AnschlussAnHoechstOderHochSpannung,object,275,2,"{'0': 235, '1': 40}"
51,InAnspruchGenommeneFlaeche,object,722,283,
52,ArtDerFlaecheIds,object,739,24,
53,DatumDesBetreiberwechsels,object,4141,1088,
54,DatumRegistrierungDesBetreiberwechsels,object,4141,1058,
55,DatumEndgueltigeStilllegung,object,343,241,
56,InAnspruchGenommeneAckerflaeche,object,207,99,
57,GeplantesInbetriebnahmedatum,object,75,44,
58,GenMastrNummer,object,104,100,
59,Einsatzverantwortlicher,object,9,9,"{'9978721000008': 1, '9900180000006': 1, '4041..."
60,WeicDisplayName,object,3,3,"{'nicht vorhanden': 1, 'E410810100000000000000..."
61,DatumBeginnVoruebergehendeStilllegung,object,59,47,
62,DatumWiederaufnahmeBetrieb,object,28,27,
63,Buergerenergie,object,1,1,{'0': 1}
64,Kraftwerksnummer,object,1,1,{'BNA1414': 1}

In [15]:
column_mapping = {
    "EinheitMastrNummer": "UnitMasterNumber",
    "DatumLetzteAktualisierung": "LastUpdatedDate",
    "LokationMaStRNummer": "LocationMasterNumber",
    "NetzbetreiberpruefungStatus": "NetworkOperatorCheckStatus",
    "NetzbetreiberpruefungDatum": "NetworkOperatorCheckDate",
    "AnlagenbetreiberMastrNummer": "PlantOperatorMasterNumber",
    "Land": "Country",
    "Bundesland": "State",
    "Landkreis": "County",
    "Gemeinde": "Municipality",
    "Gemeindeschluessel": "MunicipalityKey",
    "Postleitzahl": "PostalCode",
    "Ort": "Place",
    "Registrierungsdatum": "RegistrationDate",
    "Inbetriebnahmedatum": "CommissioningDate",
    "EinheitSystemstatus": "UnitSystemStatus",
    "EinheitBetriebsstatus": "UnitOperatingStatus",
    "NichtVorhandenInMigriertenEinheiten": "NotAvailableInMigratedUnits",
    "NameStromerzeugungseinheit": "PowerGenerationUnitName",
    "Weic_nv": "Weic_nv", # ?
    "Kraftwerksnummer_nv": "PowerPlantNumber_nv", # ?
    "Energietraeger": "EnergyCarrier",
    "Bruttoleistung": "GrossOutput",
    "Nettonennleistung": "NetRatedOutput",
    "FernsteuerbarkeitNb": "RemoteControlNb", # r?
    "Einspeisungsart": "FeedType", # ?
    "ZugeordneteWirkleistungWechselrichter": "AssignedActivePowerInverter", # ?
    "GemeinsamerWechselrichterMitSpeicher": "CommonInverterWithStorage", # ?
    "AnzahlModule": "NumberOfModules",
    "Lage": "Location",
    "Leistungsbegrenzung": "PowerLimitation",
    "EinheitlicheAusrichtungUndNeigungswinkel": "UniformOrientationAndInclinationAngle",
    "Hauptausrichtung": "MainOrientation",
    "HauptausrichtungNeigungswinkel": "MainOrientationInclinationAngle",
    "Nutzungsbereich": "UsageArea",
    "EegMaStRNummer": "EegMaStRNumber"
}

df.rename(columns=column_mapping, inplace=True)

In [16]:
dump_missing(df)

Out of 100000 entries:

                                        Amount  Percentage
LocationMasterNumber                       338        0.34
NetworkOperatorCheckDate                    75        0.08
PlantOperatorMasterNumber                  263        0.26
State                                        1        0.00
County                                       1        0.00
Municipality                                 1        0.00
MunicipalityKey                              1        0.00
PostalCode                                   1        0.00
Place                                        1        0.00
CommissioningDate                           75        0.08
RemoteControlNb                           1429        1.43
FeedType                                   699        0.70
AssignedActivePowerInverter                 11        0.01
CommonInverterWithStorage                  896        0.90
NumberOfModules                           1536        1.54
Location                                     5        0.00
PowerLimitation                           1697        1.70
UniformOrientationAndInclinationAngle     1238        1.24
MainOrientation                            853        0.85
MainOrientationInclinationAngle           1432        1.43
UsageArea                                 7615        7.62
EegMaStRNumber                              75        0.08
Nebenausrichtung                         81626       81.63
NebenausrichtungNeigungswinkel           81964       81.96
Strasse                                  89333       89.33
StrasseNichtGefunden                     88259       88.26
Hausnummer_nv                            88259       88.26
HausnummerNichtGefunden                  88259       88.26
Laengengrad                              88259       88.26
Breitengrad                              88259       88.26
FernsteuerbarkeitDr                      94169       94.17
Hausnummer                               89850       89.85
Adresszusatz                             99165       99.16
FernsteuerbarkeitDv                      94187       94.19
Gemarkung                                97701       97.70
FlurFlurstuecknummern                    97701       97.70
AnschlussAnHoechstOderHochSpannung       99725       99.72
InAnspruchGenommeneFlaeche               99278       99.28
ArtDerFlaecheIds                         99261       99.26
DatumDesBetreiberwechsels                95859       95.86
DatumRegistrierungDesBetreiberwechsels   95859       95.86
DatumEndgueltigeStilllegung              99657       99.66
InAnspruchGenommeneAckerflaeche          99793       99.79
GeplantesInbetriebnahmedatum             99925       99.92
GenMastrNummer                           99896       99.90
Einsatzverantwortlicher                  99991       99.99
WeicDisplayName                          99997      100.00
DatumBeginnVoruebergehendeStilllegung    99941       99.94
DatumWiederaufnahmeBetrieb               99972       99.97
Buergerenergie                           99999      100.00
Kraftwerksnummer                         99999      100.00

In [17]:
df["Energietraeger"]

KeyError: 'Energietraeger'