In [1]:
# Main purposes of this temporary notebook:
# 1. Check the integrity of the electricity production data downloaded from entso-e's transparency platform
# 2. Create and examine temporary DataFrames for debugging Python code

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from timeit import default_timer as timer

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Display all columns
pd.set_option('display.max_columns', None)

# Set plotting style
sns.set_style('whitegrid')
plt.rcParams['font.size'] = 10
plt.rcParams['figure.figsize'] = (11, 7)
plt.style.use('fivethirtyeight')

# 1. Data integrity and quality check for concatenated data

In [15]:
# Check raw CSV files downloaded from the transparency platform

input_folder = '/Users/shuxu_ds/workspace/neuefische_DS_bootcamp/capstone_solar/capstone_solar_energy/data/transparency/raw/'
csv_files = sorted([f for f in os.listdir(input_folder) if f.endswith('.csv')])
print(csv_files)

for csv_file in csv_files:
    csv_file = os.path.join(input_folder, csv_file)
    df = pd.read_csv(csv_file, low_memory=False)
    # df.head()
    print(df.columns[19])
    print(df.shape)
    df.info()

['2015.csv', '2016.csv', '2017.csv', '2018.csv', '2019.csv', '2020.csv', '2021.csv', '2022.csv', '2023.csv']
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35040 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35040 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35040 non-null  float64
 5   Fossil Gas  - Actual Aggregated [MW]                       35040 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35040 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35040 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35040 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35040 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35040 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35040 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35040 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35040 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35040 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35040 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35040 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35040 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35040 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35040 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35040 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35040 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35040 non-null  float64
dtypes: float64(18), object(5)
memory usage: 6.1+ MB
Solar  - Actual Aggregated [MW]
(35140, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35140 entries, 0 to 35139
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35140 non-null  object
 1   MTU                                                        35140 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35136 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35136 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35136 non-null  float64
 5   Fossil Gas  - Actual Aggregated [MW]                       35136 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35136 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35136 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35136 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35136 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35136 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35136 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35136 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35136 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35136 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35136 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35136 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35136 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35136 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35136 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35136 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35136 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35136 non-null  float64
dtypes: float64(18), object(5)
memory usage: 6.2+ MB
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35040 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35040 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35040 non-null  float64
 5   Fossil Gas  - Actual Aggregated [MW]                       35040 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35040 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35040 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35040 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35040 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35040 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35040 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35040 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35040 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35040 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35040 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35040 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35040 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35040 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35040 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35040 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35040 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35040 non-null  float64
dtypes: float64(18), object(5)
memory usage: 6.1+ MB
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35040 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35040 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35040 non-null  float64
 5   Fossil Gas  - Actual Aggregated [MW]                       35040 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35040 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35040 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35040 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35040 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35040 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35040 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35040 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35040 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35040 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35040 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35040 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35040 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35040 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35040 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35040 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35040 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35040 non-null  float64
dtypes: float64(18), object(5)
memory usage: 6.1+ MB
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35040 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35040 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35040 non-null  object
 5   Fossil Gas  - Actual Aggregated [MW]                       35040 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35040 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35040 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35040 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35040 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35040 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35040 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35040 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35040 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35040 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35040 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35040 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35040 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35040 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35040 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35040 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35040 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35040 non-null  float64
dtypes: float64(17), object(6)
memory usage: 6.1+ MB
Solar  - Actual Aggregated [MW]
(35140, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35140 entries, 0 to 35139
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35140 non-null  object
 1   MTU                                                        35140 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35136 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35136 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35136 non-null  object
 5   Fossil Gas  - Actual Aggregated [MW]                       35136 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35136 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35136 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35136 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35136 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35136 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35136 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35136 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35136 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35136 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35136 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35136 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35136 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35136 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35136 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35136 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35136 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35136 non-null  float64
dtypes: float64(17), object(6)
memory usage: 6.2+ MB
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35040 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35040 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35040 non-null  object
 5   Fossil Gas  - Actual Aggregated [MW]                       35040 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35040 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35040 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35040 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35040 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35040 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35040 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35040 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35040 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35040 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35040 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35040 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35040 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35040 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35040 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35040 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35040 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35040 non-null  float64
dtypes: float64(17), object(6)
memory usage: 6.1+ MB
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35040 non-null  float64
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35040 non-null  float64
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          35040 non-null  object
 5   Fossil Gas  - Actual Aggregated [MW]                       35040 non-null  float64
 6   Fossil Hard coal  - Actual Aggregated [MW]                 35040 non-null  float64
 7   Fossil Oil  - Actual Aggregated [MW]                       35040 non-null  float64
 8   Fossil Oil shale  - Actual Aggregated [MW]                 35040 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      35040 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       35039 non-null  float64
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             35040 non-null  float64
 12  Hydro Pumped Storage  - Actual Consumption [MW]            35040 non-null  float64
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  35040 non-null  float64
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            35040 non-null  float64
 15  Marine  - Actual Aggregated [MW]                           35040 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          35040 non-null  float64
 17  Other  - Actual Aggregated [MW]                            35040 non-null  float64
 18  Other renewable  - Actual Aggregated [MW]                  35040 non-null  float64
 19  Solar  - Actual Aggregated [MW]                            35040 non-null  float64
 20  Waste  - Actual Aggregated [MW]                            35040 non-null  float64
 21  Wind Offshore  - Actual Aggregated [MW]                    35040 non-null  float64
 22  Wind Onshore  - Actual Aggregated [MW]                     35040 non-null  float64
dtypes: float64(17), object(6)
memory usage: 6.1+ MB
Solar  - Actual Aggregated [MW]
(35044, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35044 entries, 0 to 35043
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Area                                                       35044 non-null  object
 1   MTU                                                        35044 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          35039 non-null  object
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        35039 non-null  object

In [3]:
df_long = pd.read_csv('../data/transparency/result_20150101-20230716.csv', low_memory=False)
df_long.head(1)
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315588 entries, 0 to 315587
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count   Dtype
---  ------                                                     --------------   -----
 0   Area                                                       315588 non-null  object
 1   MTU                                                        315588 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          315551 non-null  object
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        315551 non-null  object
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          315552 non-null  object
 5   Fossil Gas  - Actual Aggregated [MW]                       315551 non-null  object
 6   Fossil Hard coal  - Actual Aggregated [MW]                 315551 non-null  object
 7   Fossil Oil  - Actual Aggregated [MW]                       315552 non-null  object
 8   Fossil Oil shale  - Actual Aggregated [MW]                 315552 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      315552 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       315550 non-null  object
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             315552 non-null  object
 12  Hydro Pumped Storage  - Actual Consumption [MW]            315552 non-null  object
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  315552 non-null  object
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            315552 non-null  object
 15  Marine  - Actual Aggregated [MW]                           315552 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          312960 non-null  object
 17  Other  - Actual Aggregated [MW]                            315551 non-null  object
 18  Other renewable  - Actual Aggregated [MW]                  315551 non-null  object
 19  Solar  - Actual Aggregated [MW]                            315552 non-null  object
 20  Waste  - Actual Aggregated [MW]                            315552 non-null  object
 21  Wind Offshore  - Actual Aggregated [MW]                    315552 non-null  object
 22  Wind Onshore  - Actual Aggregated [MW]                     315552 non-null  object
dtypes: object(23)
memory usage: 55.4+ MB

In [4]:
df_long.shape

(315588, 23)

In [5]:
print(df_long['Area'].nunique())

1

In [6]:
df_long['Solar  - Actual Aggregated [MW]'].describe()

count     315552
unique     37520
top          0.0
freq      127161
Name: Solar  - Actual Aggregated [MW], dtype: object

In [7]:
print(df_long['Solar  - Actual Aggregated [MW]'].isna().sum())
df_long['Solar  - Actual Aggregated [MW]'].describe()

36

count     315552
unique     37520
top          0.0
freq      127161
Name: Solar  - Actual Aggregated [MW], dtype: object

In [8]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315588 entries, 0 to 315587
Data columns (total 23 columns):
 #   Column                                                     Non-Null Count   Dtype
---  ------                                                     --------------   -----
 0   Area                                                       315588 non-null  object
 1   MTU                                                        315588 non-null  object
 2   Biomass  - Actual Aggregated [MW]                          315551 non-null  object
 3   Fossil Brown coal/Lignite  - Actual Aggregated [MW]        315551 non-null  object
 4   Fossil Coal-derived gas  - Actual Aggregated [MW]          315552 non-null  object
 5   Fossil Gas  - Actual Aggregated [MW]                       315551 non-null  object
 6   Fossil Hard coal  - Actual Aggregated [MW]                 315551 non-null  object
 7   Fossil Oil  - Actual Aggregated [MW]                       315552 non-null  object
 8   Fossil Oil shale  - Actual Aggregated [MW]                 315552 non-null  object
 9   Fossil Peat  - Actual Aggregated [MW]                      315552 non-null  object
 10  Geothermal  - Actual Aggregated [MW]                       315550 non-null  object
 11  Hydro Pumped Storage  - Actual Aggregated [MW]             315552 non-null  object
 12  Hydro Pumped Storage  - Actual Consumption [MW]            315552 non-null  object
 13  Hydro Run-of-river and poundage  - Actual Aggregated [MW]  315552 non-null  object
 14  Hydro Water Reservoir  - Actual Aggregated [MW]            315552 non-null  object
 15  Marine  - Actual Aggregated [MW]                           315552 non-null  object
 16  Nuclear  - Actual Aggregated [MW]                          312960 non-null  object
 17  Other  - Actual Aggregated [MW]                            315551 non-null  object
 18  Other renewable  - Actual Aggregated [MW]                  315551 non-null  object
 19  Solar  - Actual Aggregated [MW]                            315552 non-null  object
 20  Waste  - Actual Aggregated [MW]                            315552 non-null  object
 21  Wind Offshore  - Actual Aggregated [MW]                    315552 non-null  object
 22  Wind Onshore  - Actual Aggregated [MW]                     315552 non-null  object
dtypes: object(23)
memory usage: 55.4+ MB

# 2. Data integrity and quality check for condensed hourly data

In [9]:
df_condense = pd.read_csv('../data/transparency/transparency_20150101-20230716_hourly.csv', low_memory=False)
df_condense.head(1)
df_condense.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74879 entries, 0 to 74878
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   area                                  74879 non-null  object
 1   mtu                                   74879 non-null  object
 2   biomass_mwh                           74879 non-null  float64
 3   fossil_brown_coal_mwh                 74879 non-null  float64
 4   fossil_coal_derived_gas_mwh           74879 non-null  float64
 5   fossil_gas_mwh                        74879 non-null  float64
 6   fossil_hard_coal_mwh                  74879 non-null  float64
 7   fossil_oil_mwh                        74879 non-null  float64
 8   fossil_oil_shale_mwh                  74879 non-null  float64
 9   fossil_peat_mwh                       74879 non-null  float64
 10  geothermal_mwh                        74879 non-null  float64
 11  hydro_pumped_storage_aggregated_mwh   74879 non-null  float64
 12  hydro_pumped_storage_consumption_mwh  74879 non-null  float64
 13  hydro_run_of_river_and_poundage_mwh   74879 non-null  float64
 14  hydro_water_reservoir_mwh             74879 non-null  float64
 15  marine_mwh                            74879 non-null  float64
 16  nuclear_mwh                           74879 non-null  float64
 17  other_mwh                             74879 non-null  float64
 18  other_renewable_mwh                   74879 non-null  float64
 19  solar_mwh                             74879 non-null  float64
 20  waste_mwh                             74879 non-null  float64
 21  wind_offshore_mwh                     74879 non-null  float64
 22  wind_onshore_mwh                      74879 non-null  float64
 23  date                                  74879 non-null  int64
 24  hour                                  74879 non-null  int64
 25  total_energy_generation_mwh           74879 non-null  float64
dtypes: float64(22), int64(2), object(2)
memory usage: 14.9+ MB

In [10]:
# Check the data types and their distributions in the 'Solar_MW' column
data_types_counts = df_condense['solar_mwh'].apply(type).value_counts()

print("Data Types in 'solar_mwh' column and their counts:")
print(data_types_counts)

# If the column has mixed data types, you can see the exact data distributions using:
data_distributions = df_condense['solar_mwh'].value_counts()

print("\nData Distributions in 'solar_mwh' column:")
print(data_distributions)

Data Types in 'solar_mwh' column and their counts:
solar_mwh
<class 'float'>    74879
Name: count, dtype: int64

Data Distributions in 'solar_mwh' column:
solar_mwh
0.00       31598
0.25         431
0.50         210
0.75         190
1.00         154
           ...
9667.00        1
9492.00        1
7513.50        1
4702.75        1
1511.25        1
Name: count, Length: 30693, dtype: int64

In [11]:
df = df_condense.copy()

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74879 entries, 0 to 74878
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   area                                  74879 non-null  object
 1   mtu                                   74879 non-null  object
 2   biomass_mwh                           74879 non-null  float64
 3   fossil_brown_coal_mwh                 74879 non-null  float64
 4   fossil_coal_derived_gas_mwh           74879 non-null  float64
 5   fossil_gas_mwh                        74879 non-null  float64
 6   fossil_hard_coal_mwh                  74879 non-null  float64
 7   fossil_oil_mwh                        74879 non-null  float64
 8   fossil_oil_shale_mwh                  74879 non-null  float64
 9   fossil_peat_mwh                       74879 non-null  float64
 10  geothermal_mwh                        74879 non-null  float64
 11  hydro_pumped_storage_aggregated_mwh   74879 non-null  float64
 12  hydro_pumped_storage_consumption_mwh  74879 non-null  float64
 13  hydro_run_of_river_and_poundage_mwh   74879 non-null  float64
 14  hydro_water_reservoir_mwh             74879 non-null  float64
 15  marine_mwh                            74879 non-null  float64
 16  nuclear_mwh                           74879 non-null  float64
 17  other_mwh                             74879 non-null  float64
 18  other_renewable_mwh                   74879 non-null  float64
 19  solar_mwh                             74879 non-null  float64
 20  waste_mwh                             74879 non-null  float64
 21  wind_offshore_mwh                     74879 non-null  float64
 22  wind_onshore_mwh                      74879 non-null  float64
 23  date                                  74879 non-null  int64
 24  hour                                  74879 non-null  int64
 25  total_energy_generation_mwh           74879 non-null  float64
dtypes: float64(22), int64(2), object(2)
memory usage: 14.9+ MB

In [13]:
print(df.shape)
print(df.columns)
df.describe().T

(74879, 26)
Index(['area', 'mtu', 'biomass_mwh', 'fossil_brown_coal_mwh',
       'fossil_coal_derived_gas_mwh', 'fossil_gas_mwh', 'fossil_hard_coal_mwh',
       'fossil_oil_mwh', 'fossil_oil_shale_mwh', 'fossil_peat_mwh',
       'geothermal_mwh', 'hydro_pumped_storage_aggregated_mwh',
       'hydro_pumped_storage_consumption_mwh',
       'hydro_run_of_river_and_poundage_mwh', 'hydro_water_reservoir_mwh',
       'marine_mwh', 'nuclear_mwh', 'other_mwh', 'other_renewable_mwh',
       'solar_mwh', 'waste_mwh', 'wind_offshore_mwh', 'wind_onshore_mwh',
       'date', 'hour', 'total_energy_generation_mwh'],
      dtype='object')

,count,mean,std,min,25%,50%,75%,max
biomass_mwh,74879.0,4.493048e+03,312.412053,0.0,4.329500e+03,4531.50,4.731250e+03,5167.00
fossil_brown_coal_mwh,74879.0,1.272760e+04,3606.732051,0.0,1.076462e+04,13505.75,1.543925e+04,19777.75
fossil_coal_derived_gas_mwh,74879.0,1.906699e+02,216.945809,0.0,0.000000e+00,0.00,4.050000e+02,753.50
fossil_gas_mwh,74879.0,4.510453e+03,2802.762193,0.0,2.254000e+03,3833.50,6.318500e+03,15033.25
fossil_hard_coal_mwh,74879.0,6.945407e+03,4310.568503,0.0,3.091250e+03,6182.25,1.027162e+04,19143.25
fossil_oil_mwh,74879.0,3.113211e+02,123.682768,0.0,2.000000e+02,293.00,4.015000e+02,1136.00
fossil_oil_shale_mwh,74879.0,0.000000e+00,0.000000,0.0,0.000000e+00,0.00,0.000000e+00,0.00
fossil_peat_mwh,74879.0,0.000000e+00,0.000000,0.0,0.000000e+00,0.00,0.000000e+00,0.00
geothermal_mwh,74879.0,2.016376e+01,5.447995,0.0,1.650000e+01,20.00,2.400000e+01,34.00
hydro_pumped_storage_aggregated_mwh,74879.0,1.090392e+03,1203.844668,0.0,2.032500e+02,623.25,1.617250e+03,9163.00
hydro_pumped_storage_consumption_mwh,74879.0,1.357737e+03,1531.157055,0.0,1.707500e+02,710.75,2.174500e+03,8657.00
hydro_run_of_river_and_poundage_mwh,74879.0,1.604339e+03,382.506327,0.0,1.312250e+03,1569.50,1.873000e+03,2867.25
hydro_water_reservoir_mwh,74879.0,1.101020e+02,81.456686,0.0,5.050000e+01,86.50,1.465000e+02,607.50
marine_mwh,74879.0,0.000000e+00,0.000000,0.0,0.000000e+00,0.00,0.000000e+00,0.00
nuclear_mwh,74879.0,7.286407e+03,2515.675025,0.0,6.389000e+03,7797.25,9.121000e+03,11471.75
other_mwh,74879.0,1.970576e+03,2537.002131,0.0,2.890000e+02,431.00,3.673000e+03,31834.75
other_renewable_mwh,74879.0,1.419860e+02,38.104440,0.0,1.152500e+02,139.00,1.710000e+02,236.00
solar_mwh,74879.0,4.940995e+03,7681.441255,0.0,0.000000e+00,159.75,7.781375e+03,40673.75
waste_mwh,74879.0,6.720140e+02,139.550584,0.0,5.922500e+02,679.50,7.810000e+02,994.25
wind_offshore_mwh,74879.0,2.259499e+03,1747.188602,0.0,7.027500e+02,1929.50,3.574375e+03,7633.25
wind_onshore_mwh,74879.0,1.020943e+04,8445.075726,0.0,3.771500e+03,7617.25,1.436312e+04,45285.25
date,74879.0,2.018850e+07,24711.217721,20150101.0,2.017022e+07,20190409.00,2.021053e+07,20230717.00
hour,74879.0,1.149985e+01,6.922151,0.0,5.500000e+00,11.00,1.700000e+01,23.00
total_energy_generation_mwh,74879.0,5.839400e+04,10871.154459,0.0,5.070200e+04,58633.00,6.655662e+04,96095.25

In [14]:
df.head(1)

,area,mtu,biomass_mwh,fossil_brown_coal_mwh,fossil_coal_derived_gas_mwh,fossil_gas_mwh,fossil_hard_coal_mwh,fossil_oil_mwh,fossil_oil_shale_mwh,fossil_peat_mwh,geothermal_mwh,hydro_pumped_storage_aggregated_mwh,hydro_pumped_storage_consumption_mwh,hydro_run_of_river_and_poundage_mwh,hydro_water_reservoir_mwh,marine_mwh,nuclear_mwh,other_mwh,other_renewable_mwh,solar_mwh,waste_mwh,wind_offshore_mwh,wind_onshore_mwh,date,hour,total_energy_generation_mwh
0,Germany (DE),20150101 00:00-01:00,3997.5,15687.25,0.0,1226.25,3219.75,176.5,0.0,0.0,10.0,913.75,588.0,1148.0,10.25,0.0,10710.5,4567.5,123.0,0.0,298.25,521.0,8849.75,20150101,0,50545.5